---
title: "predictors2025"
format: pdf
editor: visual
---

```{r}

library(forecast)
library(tidyverse)
library(prophet)

growth <- vroom::vroom("CompanyGrowth.csv")
```

```{r}
library(patchwork)

gg_inc <-growth %>%
  ggplot(aes(x = Year+((Qrtr-1)*0.25), y = Income))+
  geom_point()+
  geom_smooth(method = 'lm')

gg_prod <-growth %>%
  ggplot(aes(x = Year+((Qrtr-1)*0.25), y = Production))+
  geom_point()+
  geom_smooth(method = 'lm')

gg_sav<-growth %>%
  ggplot(aes(x = Year+((Qrtr-1)*0.25), y = Savings))+
  geom_point()+
  geom_smooth(method = 'lm')

gg_unem <-growth %>%
  ggplot(aes(x = Year+((Qrtr-1)*0.25), y = Unemployment))+
  geom_point()+
  geom_smooth(method = 'lm')

gg_inc + gg_prod + gg_sav + gg_unem
```

```{r}

vars_lst <- list(growth$Income, growth$Production, growth$Savings, growth$Unemployment)

for (i in 1:4){acf(vars_lst[[i]])}


```

```{r}

# Predict only Q1 2025 (i.e., 2025-01-01)
future_2025 <- tibble(ds = as.Date("2025-01-01"))

```

```{r}

# Convert Year + Qrtr to a proper quarterly date (first day of the quarter)
grow_prod <- growth %>%
  mutate(
    month = (Qrtr - 1) * 3 + 1,                     # 1, 4, 7, 10
    ds = as.Date(paste(Year, month, 1, sep = "-"))
  ) %>%
  select(ds, y = Production)

# Fit Prophet
proph_prod <- prophet(grow_prod)


prod_pred <- predict(proph_prod, future_2025)$yhat

prod_pred

```

```{r}
# Convert Year + Qrtr to a proper quarterly date (first day of the quarter)
grow_inc <- growth %>%
  mutate(
    month = (Qrtr - 1) * 3 + 1,                     # 1, 4, 7, 10
    ds = as.Date(paste(Year, month, 1, sep = "-"))
  ) %>%
  select(ds, y = Income)

# Fit Prophet
proph_inc <- prophet(grow_inc)


inc_pred <- predict(proph_inc, future_2025)$yhat

inc_pred

```

```{r}

# Convert Year + Qrtr to a proper quarterly date (first day of the quarter)
grow_sav <- growth %>%
  mutate(
    month = (Qrtr - 1) * 3 + 1,                     # 1, 4, 7, 10
    ds = as.Date(paste(Year, month, 1, sep = "-"))
  ) %>%
  select(ds, y = Savings)

# Fit Prophet
proph_sav <- prophet(grow_sav)


sav_pred <- predict(proph_sav, future_2025)$yhat

sav_pred

```

```{r}

# Convert Year + Qrtr to a proper quarterly date (first day of the quarter)
grow_unem <- growth %>%
  mutate(
    month = (Qrtr - 1) * 3 + 1,                     # 1, 4, 7, 10
    ds = as.Date(paste(Year, month, 1, sep = "-"))
  ) %>%
  select(ds, y = Unemployment)

# Fit Prophet
proph_unem <- prophet(grow_unem)


unem_pred <- predict(proph_unem, future_2025)$yhat

unem_pred


```
